services:
  api:
    build:
      context: .
      args:
        UID: ${UID:-1001}
        GID: ${GID:-1001}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./chroma_store:/app/chroma_store
    env_file:
      - .env
    user: "${UID:-1001}:${GID:-1001}"
